server:
  port: 9092

spring:
  application:
     name: CATALOGUE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/udemy_codedecode_catalogueDB
    username: root
    password: Metallica_911
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  profiles:
    active: localhost
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

